### ISSUE TITLE
Données brutes vs modèle cinq étoiles

### ISSUE THREAD

**Issue by joelgombin** [datactivist/ardeche#4]
Plus un questionnement général qu'un problème à résoudre dans le texte : comment Bernes-Lee articule--t-il la demande "raw data now" avec le modèle 5-stars ? Il me semble qu'avec ce dernier on s'éloigne clairement de données "brutes" (au sens "telles qu'elles sont dans les ordinateurs de l'administration") pour aller vers des données retravaillées et enrichies...

**Comment by samgoeta** [comment]
Je suis d'accord que ça peut paraitre un peu contradictoire. Mais l'idée du 5-star model c'est de proposer une marche à suivre : d'abord ouvrir puis retravailler/améliorer ensuite. 
Si tu ré-écoutes la conférence TED, Berners-Lee plaide pour qu'on ouvre d'abord les données brutes avant de les améliorer. Il ne dit pas que les données doivent toujours rester brutes, intactes. Le sens aussi de cette demande, c'est de réclamer des données qui ne soient pas agrégées.

**Comment by joelgombin** [comment]
réintègre cette excellente explication dans le texte ?
